### ISSUE TITLE
TODO-List (Post feature requests here!)

### ISSUE THREAD

**Issue by robske110** [robske110/BanWarn#1]
Ideas are always welcome, please post them in this issue!
### 2.0.0 (InDev)
- [ ] **Complete Class-style rewrite**
- [ ] **Make BanWarn fit for the XBOX era**
- [ ] **Forms, what else do you expect?**
- [ ] Handling players using multiple names over one ClientID better (no high priority anymore, XBOX)
- [ ] Handling players that use two devices with the same playerName.
- [ ] BanHammer Item [_external extension_]
  - [ ] Configurable ItemID in config
- [ ] Change Usage to `/warn <PlayerName> [Points] <Reason>` or keep the old style and search for the last number.
- [ ] Configurable **commands** per Warn-Point [_external extension_]
- [ ] /report command for users [_external extension_]
- [ ] Config:
  -  [ ] SQL-settings
  -  [ ] ...
- [ ] TempBan (Maybe configurable)
- [ ] Make all players warnable (Not only warned or online Players)
- [ ] API
- [ ] Improved Data provider
- [ ] SQL
- [x] Language Translation file
#### 1.2.0 (RELEASED):
- [x] **Pardon** command  [Already in **1.2.0-InDev-beta2**]
- [x] **AutoBan** on join if over max points (If he was not online as he reached the max points!) [Already in **1.2.0-InDev-alpha1**]
- [x] Config:
  - [x] IP-Ban true/false [Default: true] [Already in **1.2.0-InDev-alpha2**]
  - [x] Client-Ban true/false [Default: true] [Already in **1.2.0-InDev-alpha2**]
  - [x] Notify-Mode 1/2 [Default: 1] [Already in **1.2.0-InDev-beta2**]
#### 1.1.0 (RELEASED):
- [x] **ClientID** for WarnPoints identification [Already in **1.1.0-InDev-alpha3**]
- [x] **Config** with setting for max-warn-points [Already in **1.1.0-InDev-alpha6**]
- [x] You can now use  `/warn <PlayerName> <Reason> [Points]` @thebigsmileXD [Already in **1.1.0-InDev-alpha8**]
- [x] Ban with IP **and ClientID** [Already in **1.1.0-InDev-alpha7**]
- [x] Fix Ban-display [Already in **1.1.0-InDev-beta1**]
- [x] **English version**

**Comment by BlackShadow1** [comment]
Code looks that if the player is not online, the warninfo give 0 warnpoint, if he/she is, it give the warn point that he/she really have. Look at line 162, if I am wrong, sorry.

**Comment by Aericio** [comment]
Auto Warning maybe? For example they could type a swear word that they spaced out (ex. F \* \* K ), and most censoring plugins do not block that. Maybe if you can add some "tracking" thing that tracks that and it would auto-warn them? But also have a feature that takes that line the person sent and make put it (for example) into a blah.txt file that, when you run a command in game, it will show who has been auto-warned and if the warn should be right or not, along with the text they wrote.

**Comment by robske110** [comment]
Hmm. That sounds more like a external plugin I'll make using the upcoming API in this plugin. But I'll definitely stick to that Auto-warned listing (warned from other plugins)
I think I'll do this within the 2.0.0 rewrite...

**Comment by Aericio** [comment]
Oh also, maybe you can have a feature where players can see their warnings, besides the one-time message when we warn them. And maybe a way for us to remove warns from them besides going in config?

**Comment by robske110** [comment]
Yes, that'll be added

**Comment by SalmonDE** [comment]
Does this plugin support MySQL? So multiple servers can use the same bans.

**Comment by robske110** [comment]
Right now, no, but this is on the todo list for 2.0.0 wich will be developed as soon as 1.2.0 is released
You could modify the config-save-path here https://github.com/robske110/BanWarn/blob/master/English/src/robske_110/BanWarn/Main.php#L25-L29 (replace $this->getDataFolder with "path_to_file" and then every server could access that

**Comment by SalmonDE** [comment]
Is it also possible if you run the servers on different machines?

**Comment by robske110** [comment]
No, not yet :(
But as i said it will be supported in 2.0.0 allthough this update may take severeal months (probably 2)

**Comment by robske110** [comment]
I just wonder if it would support ftp:// you may want to give it a try.

**Comment by SalmonDE** [comment]
Can it work with sftp, too?

**Comment by Aericio** [comment]
Who cares about a secure FTP, its ran on your home server so there isn't much data transfer from far away...

**Comment by SalmonDE** [comment]
It was the default server so I used it. I don't want to switch now xd and I also connect to it from outside

**Comment by robske110** [comment]
I think it's best to wait for me to release the first 2.0.0 betas (the alphas will be probably useless)

**Comment by Aericio** [comment]
`Usage: /warn <PlayerName> <Reason> [Points]`
Maybe instead of doing points last, can you make it to:
`Usage: /warn <PlayerName>  [Points] <Reason>`
This allowed people to make the ban reason longer, so it isn't something like YouSmellLikePooBanned

**Comment by robske110** [comment]
The problem is that then i can't make the points optional. Wait can I? I can. Lol will do this for 1.3.0 but now gonna release 1.2.0 as no bug reports have been found by me

**Comment by Aericio** [comment]
Ok :D

**Comment by inxomnyaa** [comment]
@robske110 why not using the option i told you, that you check if the last part is a number?

**Comment by Aericio** [comment]
Your travis died lol.

**Comment by robske110** [comment]
Cause it'a using php5
Will fix that somewhen

**Comment by ghost** [comment]
There must be support for MYSQL, used for four servers.

**Comment by robske110** [comment]
I'm currently woring on version 2.0.0 but that will really take some time.
Expect beta1 in 3weeks

**Comment by Aericio** [comment]
3 weeks pasts... :D

**Comment by inxomnyaa** [comment]
aaand /warn player unendliche scheiß nachricht 4

**Comment by robske110** [comment]
Well, some work has been done. The plugin starts somewhat and doesn't work at all. I'd love to have a helping hand. But well, I'm on vacation right now with veryy limited time.

**Comment by Aericio** [comment]
Ask @SalmonGER (theunmightycoder) to help you? It would probably give him more coding knowledge :D

**Comment by robske110** [comment]
Sorry for the delays in developing this. Going to release 1.2.1 to fix some bugs and continue working on 2.0.0
I can say: BanWarn 2.0.0 will be (at least in a working order) released this year. Yey

**Comment by pnyyhz** [comment]
How can I unban players after reaching max points?

**Comment by robske110** [comment]
`/warnpardon <playerName>`

**Comment by thebigsmileXD** [comment]
Todo: delete banwarn

**Comment by Aericio** [comment]
That would fix so many bugs!

**Comment by Aericio** [comment]
Allow user to change the holy message when the user is warned. The holy warn message may hurt some people.

**Comment by robske110** [comment]
:D 
And yes, translation ~will be~ *is* implemented

**Comment by Aericio** [comment]
mm banwarn 2.0.0 tastes great in 2018

**Comment by robske110** [comment]
Planning to re-start development of BanWarn 2.0.0. Let's see where we get.
